export interface SensorName {
  sensorId: number
  sensorName: string
}

// 传感器名称
export const SENSOR_NAME_LIST: SensorName[] = [
  {
    "sensorId": 1,
    "sensorName": "加速度传感器"
  },
  {
    "sensorId": 2,
    "sensorName": "陀螺仪传感器"
  },
  {
    "sensorId": 5,
    "sensorName": "环境光传感器"
  },
  {
    "sensorId": 6,
    "sensorName": "磁场传感器"
  },
  {
    "sensorId": 8,
    "sensorName": "气压计传感器"
  },
  {
    "sensorId": 10,
    "sensorName": "霍尔传感器"
  },
  {
    "sensorId": 12,
    "sensorName": "接近光传感器"
  },
  {
    "sensorId": 13,
    "sensorName": "湿度传感器"
  },
  {
    "sensorId": 256,
    "sensorName": "方向传感器"
  },
  {
    "sensorId": 257,
    "sensorName": "重力传感器"
  },
  {
    "sensorId": 258,
    "sensorName": "线性加速度传感器"
  },
  {
    "sensorId": 259,
    "sensorName": "旋转矢量传感器"
  },
  {
    "sensorId": 260,
    "sensorName": "环境温度传感器"
  },
  {
    "sensorId": 261,
    "sensorName": "未校准磁场传感器"
  },
  {
    "sensorId": 263,
    "sensorName": "未校准陀螺仪传感器"
  },
  {
    "sensorId": 264,
    "sensorName": "有效运动传感器"
  },
  {
    "sensorId": 265,
    "sensorName": "计步检测传感器"
  },
  {
    "sensorId": 266,
    "sensorName": "计步传感器"
  },
  {
    "sensorId": 278,
    "sensorName": "心率传感器"
  },
  {
    "sensorId": 280,
    "sensorName": "佩戴检测传感器"
  },
  {
    "sensorId": 281,
    "sensorName": "未校准加速度计传感器"
  }
]
